In [1]:
#Numpy is a python pakage or a library for scitific computing ,numeric  computing and mainly used in data scienc and machine learning
#numpy introduce a power full data structure called NDarray (n_dimensional arry)

#array- array is a collection homogenuos element denoted by [] with space seperated values 
#array allows used to stored and manipulate massive data and incrideble speed

In [2]:
%timeit [j**4 for j in range(1,1000)]

134 μs ± 4.57 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [6]:
import numpy as np

In [7]:
%timeit np.arange(1,1000)**4

17.6 μs ± 610 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
#create array with numpy array() function
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
int64


In [9]:
l=[10,20,30,"40",50.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

['10' '20' '30' '40' '50.5']
<class 'numpy.ndarray'>
1
(5,)
5
<U32


In [10]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [13]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)
12
int64


In [19]:
arr=np.array([[[1,2,3,4,5]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[1 2 3 4 5]]]
<class 'numpy.ndarray'>
3
(1, 1, 5)
5
int64


In [2]:
import numpy as np

In [3]:
#np.arange([start],stop,[step])
#it always return a one dimension array.
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
arr=np.arange(1,13)
print(arr)
arr1=arr.reshape(3,4)
print(arr1)
print(arr1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [7]:
#index-position of an element in a given array
#indexing-technique for accessing single elements from a given array

arr=np.arange(10,16)
print(arr)
print(arr[0])
print(arr[-1])

[10 11 12 13 14 15]
10
15


In [8]:
arr=np.arange(10,20).reshape(2,5)
print(arr)
print()
print(arr[0])
print(arr[0][-1])
print(arr[1][2])

[[10 11 12 13 14]
 [15 16 17 18 19]]

[10 11 12 13 14]
14
17


In [11]:
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
print()
print(arr[-1])
print()
print(arr[1][0])
print()
print(arr[1][0][1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[ 7  8  9]
 [10 11 12]]

[7 8 9]

8


In [19]:
#create two dimensional array having 8 element using function?
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


[[10 20 30 40]
 [50 60 70 80]]
2
(2, 4)
8
int64


In [23]:
#create three dimensional array using arange function having 36 elements?

arr=np.arange(1,37).reshape(2,3,6)
print(arr)
print()
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]

 [[19 20 21 22 23 24]
  [25 26 27 28 29 30]
  [31 32 33 34 35 36]]]

3
(2, 3, 6)
36
int64


In [4]:
import numpy as np

#iteration
arr=np.arange(10,15)
print(arr)
for i in arr:
    print(i)

[10 11 12 13 14]
10
11
12
13
14


In [6]:
#indirect iteration
arr=np.arange(10,15)
print(arr)
for i in range(len(arr)):
    print(i,arr[i])

[10 11 12 13 14]
0 10
1 11
2 12
3 13
4 14


In [7]:
arr=np.arange(10,15)
print(arr)
print(len(arr))
count=0
for i in arr:
    count=count+1
print(count)

[10 11 12 13 14]
5
5


In [8]:
arr=np.arange(10,19).reshape(3,3)
print(arr)
print()
for i in arr:
    for j in i:
        print(j)

[[10 11 12]
 [13 14 15]
 [16 17 18]]

10
11
12
13
14
15
16
17
18


In [9]:
#np.nditer(arrayobj)
arr=np.arange(10,22).reshape(2,2,3)
print(arr)
for i in np.nditer(arr):
    print(i)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]
10
11
12
13
14
15
16
17
18
19
20
21


In [11]:
#np.ndenumerate(arrayobj)- return index and value
arr=np.arange(10,22).reshape(2,2,3)
print(arr)
for index,value in np.ndenumerate(arr):
    print(index,value)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]
(0, 0, 0) 10
(0, 0, 1) 11
(0, 0, 2) 12
(0, 1, 0) 13
(0, 1, 1) 14
(0, 1, 2) 15
(1, 0, 0) 16
(1, 0, 1) 17
(1, 0, 2) 18
(1, 1, 0) 19
(1, 1, 1) 20
(1, 1, 2) 21


In [12]:
#create one 1-d array having 5 elemnts(float)?take input at runtime using array function?
l=[]
for i in l
