In [1]:
#Numpy is a python pakage or a library for scitific computing ,numeric  computing and mainly used in data scienc and machine learning
#numpy introduce a power full data structure called NDarray (n_dimensional arry)

#array- array is a collection homogenuos element denoted by [] with space seperated values 
#array allows used to stored and manipulate massive data and incrideble speed

In [2]:
%timeit [j**4 for j in range(1,1000)]

134 μs ± 4.57 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [3]:
import numpy as np

In [4]:
%timeit np.arange(1,1000)**4

9.93 μs ± 500 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
#create array with numpy array() function
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
int64


In [9]:
l=[10,20,30,"40",50.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

['10' '20' '30' '40' '50.5']
<class 'numpy.ndarray'>
1
(5,)
5
<U32


In [10]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [13]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)
12
int64


In [15]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
int64
