In [ ]:
# it is a fundamental package for scientific computing in python
# ti isa python libary that provides a multi dinemsional array object and drivrd objects

# array: it is a grid of value and contain infprmation about ,how to locat an elements and hoe to interpert

In [3]:
import numpy as np
l=[10,20,30,40]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10 20 30 40]
<class 'numpy.ndarray'>
1
(4,)
4
int64


In [12]:
import numpy as np
l=[10,20,30,40,40.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
1
(5,)
5
float64


In [13]:
import numpy as np
l=[10,'20',30,40,40.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

['10' '20' '30' '40' '40.5']
<class 'numpy.ndarray'>
1
(5,)
5
<U32


In [15]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2
(2, 3)
6
int64


In [17]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)
12
int64


In [18]:
arr=np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [4]:
arr=np.arange(1,9,1)
print(arr)
arr1=arr.reshape(1,8)
print(arr1)

[1 2 3 4 5 6 7 8]
[[1 2 3 4 5 6 7 8]]


In [5]:
arr=np.arange(1,9,1)
print(arr)
arr1=arr.reshape(8,1)
print(arr1)

[1 2 3 4 5 6 7 8]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [22]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [7]:
%timeit [j**1000 for j in range(1,9)]

17.3 μs ± 2.08 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
import numpy as np
%timeit np.arange(1,9)**1000

6.47 μs ± 753 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
# array()
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
4
int64


In [11]:
arr=np.array([[1,2,3,4]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3 4]]
<class 'numpy.ndarray'>
2
(1, 4)
4
int64


In [12]:
arr=np.array([[[1,2,3,4]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[1 2 3 4]]]
<class 'numpy.ndarray'>
3
(1, 1, 4)
4
int64


In [32]:
arr=np.array([1,2,3,4],ndmin=10)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
<class 'numpy.ndarray'>
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)
4
int64


In [17]:
# arange()
# arange(start,stop,step)
# always return 1-d array
arr=np.arange(1,19)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [20]:
arr=np.arange(1,19).reshape(3,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [21]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [22]:
# indexcing 1d
arr=np.array([10,20,30,40,50])
print(arr)
print(arr[0])
print(arr[-1])

[10 20 30 40 50]
10
50


In [23]:
#2D
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(arr[1])
print(arr[1][2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
7


In [24]:
#3D
arr=np.arange(1,28).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [25]:
# DIRECT ITERATION 
arr=np.array([10,20,30,40,50])
print(arr)
for i in arr:
    print(i)

[10 20 30 40 50]
10
20
30
40
50


In [26]:
# indirect itrration
arr=np.array([10,20,30,40,50])
for i in range(len(arr)):
    print(arr[i])

10
20
30
40
50


In [27]:
#2d 
arr=np.arange(1,13).reshape(3,4)
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [28]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
for i in arr:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [29]:
arr=np.arange(1,28).reshape(3,3,3)
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [30]:
arr=np.arange(1,28).reshape(3,3,3)
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(1, 0, 0) 10
(1, 0, 1) 11
(1, 0, 2) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 2, 0) 16
(1, 2, 1) 17
(1, 2, 2) 18
(2, 0, 0) 19
(2, 0, 1) 20
(2, 0, 2) 21
(2, 1, 0) 22
(2, 1, 1) 23
(2, 1, 2) 24
(2, 2, 0) 25
(2, 2, 1) 26
(2, 2, 2) 27
