In [ ]:
# it is a fundamental package for scientific computing in python
# ti isa python libary that provides a multi dinemsional array object and drivrd objects

# array: it is a grid of value and contain infprmation about ,how to locat an elements and hoe to interpert

In [3]:
import numpy as np
l=[10,20,30,40]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10 20 30 40]
<class 'numpy.ndarray'>
1
(4,)
4
int64


In [12]:
import numpy as np
l=[10,20,30,40,40.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
1
(5,)
5
float64


In [13]:
import numpy as np
l=[10,'20',30,40,40.5]
arr=np.array(l)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

['10' '20' '30' '40' '40.5']
<class 'numpy.ndarray'>
1
(5,)
5
<U32


In [15]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2
(2, 3)
6
int64


In [17]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)
12
int64


In [18]:
arr=np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [4]:
arr=np.arange(1,9,1)
print(arr)
arr1=arr.reshape(1,8)
print(arr1)

[1 2 3 4 5 6 7 8]
[[1 2 3 4 5 6 7 8]]


In [5]:
arr=np.arange(1,9,1)
print(arr)
arr1=arr.reshape(8,1)
print(arr1)

[1 2 3 4 5 6 7 8]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [22]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [7]:
%timeit [j**1000 for j in range(1,9)]

17.3 μs ± 2.08 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
import numpy as np
%timeit np.arange(1,9)**1000

6.47 μs ± 753 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
# array()
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
4
int64


In [11]:
arr=np.array([[1,2,3,4]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3 4]]
<class 'numpy.ndarray'>
2
(1, 4)
4
int64


In [12]:
arr=np.array([[[1,2,3,4]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[1 2 3 4]]]
<class 'numpy.ndarray'>
3
(1, 1, 4)
4
int64


In [32]:
arr=np.array([1,2,3,4],ndmin=10)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
<class 'numpy.ndarray'>
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)
4
int64


In [17]:
# arange()
# arange(start,stop,step)
# always return 1-d array
arr=np.arange(1,19)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [20]:
arr=np.arange(1,19).reshape(3,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [21]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [22]:
# indexcing 1d
arr=np.array([10,20,30,40,50])
print(arr)
print(arr[0])
print(arr[-1])

[10 20 30 40 50]
10
50


In [23]:
#2D
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(arr[1])
print(arr[1][2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
7


In [24]:
#3D
arr=np.arange(1,28).reshape(3,3,3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [25]:
# DIRECT ITERATION 
arr=np.array([10,20,30,40,50])
print(arr)
for i in arr:
    print(i)

[10 20 30 40 50]
10
20
30
40
50


In [26]:
# indirect itrration
arr=np.array([10,20,30,40,50])
for i in range(len(arr)):
    print(arr[i])

10
20
30
40
50


In [27]:
#2d 
arr=np.arange(1,13).reshape(3,4)
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [28]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
for i in arr:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [29]:
arr=np.arange(1,28).reshape(3,3,3)
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [30]:
arr=np.arange(1,28).reshape(3,3,3)
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(1, 0, 0) 10
(1, 0, 1) 11
(1, 0, 2) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 2, 0) 16
(1, 2, 1) 17
(1, 2, 2) 18
(2, 0, 0) 19
(2, 0, 1) 20
(2, 0, 2) 21
(2, 1, 0) 22
(2, 1, 1) 23
(2, 1, 2) 24
(2, 2, 0) 25
(2, 2, 1) 26
(2, 2, 2) 27


In [1]:
#special filled array
import numpy as np

In [3]:
#zero filled array
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [4]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
arr=np.zeros((3,3,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [6]:
#one filled array
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [7]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
arr=np.ones((3,3,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [9]:
#diagonal array
arr=np.eye(3,3)
print(arr)
print(arr[::-1])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [10]:
#evenly spaced array
#linspace(start,stop,size=50)
arr=np.linspace(1,10)
print(arr)
print(len(arr))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
50


In [11]:
arr=np.linspace(0,20,5)
print(arr)

[ 0.  5. 10. 15. 20.]


In [12]:
#random-uniform distributed
arr=np.random.rand(2,3)
print(arr)

[[0.61978138 0.03554079 0.5609023 ]
 [0.95731339 0.48207059 0.03078352]]


In [14]:
#randn
#standard normal distributed
#mean=0 and std=1
age=np.random.randn(15)
print(age)
print(np.mean(age))
print(np.std(age))

[-1.06862655  0.3764054  -0.06940125 -1.2157331  -1.60182536 -0.11774241
  0.05225044  0.3885386   0.220943   -1.40603554 -0.34582256  1.89246108
  2.23814157 -0.22959903  1.3274592 ]
0.029427565207843762
1.096593905621102


In [16]:
arr=np.random.randint(10,100,10)
print(arr)

[22 89 81 10 14 95 50 41 47 29]


In [18]:
arr=np.random.randint(10,50,(5,5))
print(arr)

[[40 46 19 27 13]
 [47 42 33 31 41]
 [25 16 48 29 49]
 [17 26 27 48 40]
 [18 13 32 20 28]]


In [19]:
arr=np.random.randn(1000)
print(arr)
print(np.mean(arr))

[-8.32863729e-01  7.96477555e-01  1.76555809e+00 -1.78392851e-01
 -4.67506199e-01  1.11194509e-01  1.58604003e+00  3.68211058e-02
  7.75713452e-01 -9.91559862e-01 -1.80031038e-01  3.36827337e-01
  2.63310628e-01  1.53880204e+00 -1.26692808e+00  1.55563838e-01
 -3.83179366e-01  6.40193756e-02  2.61367875e-01  7.49807674e-01
 -2.80271740e-01  4.13473053e-01 -1.70733275e+00  1.81653479e-01
 -7.45817881e-01 -1.30289748e-01  1.86239995e+00  6.14862845e-01
  6.23485387e-01  1.13306312e+00 -2.00818663e-04 -1.62181248e-01
  2.06507988e-01 -1.41222382e+00  4.50266376e-01  1.54662632e+00
  1.52314274e+00  1.00825692e-02 -7.23086856e-01  6.11462992e-01
  3.99262205e-01 -1.60360378e+00  1.71138749e-01 -7.13395955e-01
  1.04241016e+00  1.11951405e+00  4.74897468e-01  1.87058198e+00
  1.25611593e+00 -3.60979920e-01 -8.89874637e-02  6.60657333e-01
 -1.11490244e+00 -1.04146109e+00  1.76912558e+00 -6.17433034e-01
  2.71560267e-01 -3.03910823e-01  3.92322881e-01  1.29919817e+00
  2.81133684e-01  1.63847

In [21]:
!git add .

In [22]:
!git commit -m "learned numpay"

[main e31cf01] learned numpay
 3 files changed, 1831 insertions(+), 5 deletions(-)
 create mode 100644 python-basics/.ipynb_checkpoints/numpay (1)-checkpoint.ipynb


In [23]:
!git push

To https://github.com/rosesolanki29/daily-python-data-lab.git
   a2312c0..e31cf01  main -> main
